/**
 * Entidades de demonstração (mesmo conjunto conceitual do MockDataService do Angular).
 * Datas em string ISO para o contrato ApiEntityResponse.
 */
module.exports = [
  {
    id: '1',
    name: 'Empresa Verde Sustentável Ltda',
    document: '11222333000181',
    documentType: 'cnpj',
    score: 15,
    riskLevel: 'Baixo',
    occurrences: [
      {
        id: 'occ-1',
        date: '2023-06-15',
        description:
          'Advertência por descarte irregular de resíduos - situação regularizada',
        status: 'Baixado',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/123456',
        category: 'Ambiental IBAMA',
      },
    ],
  },
  {
    id: '2',
    name: 'Indústria Amarela S.A.',
    document: '22333444000181',
    documentType: 'cnpj',
    score: 42,
    riskLevel: 'Médio',
    occurrences: [
      {
        id: 'occ-2',
        date: '2024-03-20',
        description: 'Auto de infração por emissão de poluentes acima do permitido',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/234567',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-3',
        date: '2024-01-10',
        description: 'Multa por operação sem licença ambiental válida',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/234568',
        category: 'Ambiental IBAMA',
      },
    ],
  },
  {
    id: '3',
    name: 'Construtora Laranja Ltda',
    document: '33444555000181',
    documentType: 'cnpj',
    score: 68,
    riskLevel: 'Alto',
    occurrences: [
      {
        id: 'occ-4',
        date: '2024-05-12',
        description: 'Embargo de obra por desmatamento ilegal em área de preservação',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/345678',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-5',
        date: '2024-04-08',
        description: 'Auto de infração por degradação de área de APP',
        status: 'Ativo',
        source: 'ICMBio',
        sourceUrl: 'https://icmbio.gov.br/consulta/456789',
        category: 'Ambiental ICMBio',
      },
      {
        id: 'occ-6',
        date: '2024-02-28',
        description: "Multa por poluição de curso d'água",
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/345679',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-7',
        date: '2023-11-15',
        description: 'Autuação por descumprimento de normas de segurança do trabalho',
        status: 'Ativo',
        source: 'MTE',
        sourceUrl: 'https://mte.gov.br/consulta/567890',
        category: 'Trabalhista',
      },
    ],
  },
  {
    id: '4',
    name: 'Mineradora Vermelha S.A.',
    document: '44555666000181',
    documentType: 'cnpj',
    score: 89,
    riskLevel: 'Crítico',
    occurrences: [
      {
        id: 'occ-8',
        date: '2024-06-01',
        description: 'Embargo total de atividades por contaminação de lençol freático',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/456780',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-9',
        date: '2024-05-20',
        description: 'Auto de infração por mineração em área de unidade de conservação',
        status: 'Ativo',
        source: 'ICMBio',
        sourceUrl: 'https://icmbio.gov.br/consulta/567891',
        category: 'Ambiental ICMBio',
      },
      {
        id: 'occ-10',
        date: '2024-04-15',
        description: 'Multa por destruição de habitat de espécie ameaçada',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/456781',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-11',
        date: '2024-03-10',
        description: 'Auto de infração por operação sem licença',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/456782',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-12',
        date: '2024-02-05',
        description: 'Multa por emissão de poluentes atmosféricos',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/456783',
        category: 'Ambiental IBAMA',
      },
      {
        id: 'occ-13',
        date: '2024-01-20',
        description: 'Autuação por trabalho em condições degradantes',
        status: 'Ativo',
        source: 'MTE',
        sourceUrl: 'https://mte.gov.br/consulta/678901',
        category: 'Trabalhista',
      },
      {
        id: 'occ-14',
        date: '2023-12-10',
        description: 'Multa por descumprimento de normas de segurança',
        status: 'Ativo',
        source: 'MTE',
        sourceUrl: 'https://mte.gov.br/consulta/678902',
        category: 'Trabalhista',
      },
      {
        id: 'occ-15',
        date: '2023-10-05',
        description: 'Sanção administrativa por irregularidades em documentação',
        status: 'Ativo',
        source: 'ANM',
        sourceUrl: 'https://anm.gov.br/consulta/789012',
        category: 'Administrativo',
      },
    ],
  },
  {
    id: '6',
    name: 'Eco Limpo Comércio Ltda',
    document: '60746977000184',
    documentType: 'cnpj',
    score: 0,
    riskLevel: 'Baixo',
    occurrences: [],
  },
  {
    id: '5',
    name: 'João da Silva Teste',
    document: '12345678909',
    documentType: 'cpf',
    score: 35,
    riskLevel: 'Médio',
    occurrences: [
      {
        id: 'occ-16',
        date: '2024-02-15',
        description: 'Auto de infração por pesca ilegal em área protegida',
        status: 'Ativo',
        source: 'IBAMA',
        sourceUrl: 'https://ibama.gov.br/consulta/890123',
        category: 'Ambiental IBAMA',
      },
    ],
  },
];
